- name: Install engineering fedora packages
  dnf:
    name:
      - freecad # General purpose 3D CAD modeler
    state: present
  become: true
      
- include_tasks: superslicer.yml # PrusaSlicer fork (which is a slic3r fork)
